# fly.toml app configuration file generated for abc-2-1718877385-client on 2024-06-20T09:57:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abc-2-1718877385-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
